# Generated by Django 4.2.7 on 2023-12-11 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_remove_account_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='type',
            new_name='tran_type',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user_name',
            new_name='user',
        ),
    ]
