# Generated by Django 4.2.7 on 2023-12-11 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_alter_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account_id',
        ),
    ]
