# Generated by Django 4.2.7 on 2023-12-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermealcost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermealcost',
            name='week',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='date',
        ),
        migrations.AddField(
            model_name='meal',
            name='per_meal_cost',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='MealCost',
        ),
        migrations.DeleteModel(
            name='UserMealCost',
        ),
    ]
