# Generated by Django 4.2.7 on 2023-12-11 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_account_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user_id',
            new_name='user',
        ),
    ]
