# Generated by Django 4.2.7 on 2023-12-05 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userex_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userex',
            old_name='type',
            new_name='role',
        ),
    ]
