# Generated by Django 4.2.7 on 2023-12-05 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_type_userex_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEx',
        ),
    ]
