# Generated by Django 4.2.7 on 2023-12-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEx',
        ),
    ]
