# Generated by Django 4.2.7 on 2023-12-05 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userex',
            old_name='user_name',
            new_name='username',
        ),
    ]
