# Generated by Django 4.2.7 on 2023-12-05 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_rename_user_name_userex_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userex',
            name='username',
        ),
        migrations.AddField(
            model_name='userex',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
